# Generated by Django 5.1 on 2024-09-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='private',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
